trigger:
- master

pr:
- master

pool:
  vmImage: 'windows-latest'
strategy:
  matrix:
    Python27:
      python.version: '2.7'
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'
  condition: eq(variables['python.version'], '2.7')

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    githubToken: ge-flight-analytics
  displayName: 'Use Python $(python.version)'
  condition: ne(variables['python.version'], '2.7')

- script: |
    python -m pip install --upgrade pip
    pip install .
  displayName: 'Install dependencies'

- script: |
    pip install -r dev-requirements.txt
    python -m pytest tests 
  displayName: 'pytest'
